POST http://localhost:4000/api/user/otp-secret
Content-Type: application/json

{
    "name": "fffffffffff",
    "password": "2123123123"
}

###

POST http://localhost:4000/api/user/otp-validar
Content-Type: application/json

{
    "name": "fffffffffff",
    "token": "6154647"
}